---
abstract: 'include output of commands in your pod'
author:
  - 'Arthur Axel "fREW" Schmidt <frioux+cpan@gmail.com>'
build_requires:
  Pod::Elemental: '0'
  Pod::Elemental::Transformer::Pod5: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pod-Weaver-Plugin-Exec
requires:
  Capture::Tiny: '0'
  Moose: '0'
  Moose::Autobox: '0'
  Pod::Elemental::Transformer: '0'
  Pod::Weaver::Role::Dialect: '0'
  namespace::clean: '0'
  perl: '5.014'
resources:
  bugtracker: https://github.com/frioux/Pod-Weaver-Plugin-Exec/issues
  homepage: https://github.com/frioux/Pod-Weaver-Plugin-Exec
  repository: https://github.com/frioux/Pod-Weaver-Plugin-Exec.git
version: '0.001000'
